import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Upfesto",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: "#FFCE00",
          colorTextOnPrimaryBackground: "#000000",
          borderRadius: "0.8rem",
        },
        elements: {
          card: "shadow-none rounded-xl w-full max-w-screen-xl mx-auto",
          rootBox: "w-full",
          navbar: "hidden sm:block",
          navbarMobileMenuRow: "hidden",
          headerTitle: "text-2xl font-semibold",
        },
        signIn: {
          elements: {
            rootBox: "relative h-[80vh]",
            card: "w-full max-w-[500px] sm:absolute sm:top-1/2 sm:left-1/2 sm:transform sm:-translate-y-1/2 sm:-translate-x-1/2",
          },
        },
        signUp: {
          elements: {
            rootBox: "relative h-[80vh]",
            card: "w-full max-w-[500px] sm:absolute sm:top-1/2 sm:left-1/2 sm:transform sm:-translate-y-1/2 sm:-translate-x-1/2",
          },
        },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <NavBar />
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
};

export default RootLayout;
